[package]
authors = ["Ben Scholar <bbs27@case.edu>"]
edition = "2018"
name = "adaptor-gui"
version = "0.1.0"
[dependencies]
env_logger = "*"
gio = "*"
glib = "*"
gtk = "0.9"
hex = "*"
log = "*"
structopt = "*"
tempfile = "*"
